//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Zao.CrsPlat.Model
{

	/// <summary>
	/// 实体类Sys_table_dic 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_table_dic")]
	[Serializable]
	public partial class Sys_table_dic : Entity 
	{
		#region Model
		private int? _class_id;
		private int _object_id;
		private string _tableName;
		private string _tableDescription;
		private string _tableOwner;
		private string _creater;
		private DateTime? _createTime;
		private int? _status;
		private string _remark;
		/// <summary>
		/// 
		/// </summary>
		public int? class_id
		{
			get{ return _class_id; }
			set
			{
				this.OnPropertyValueChange(_.class_id,_class_id,value);
				this._class_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int object_id
		{
			get{ return _object_id; }
			set
			{
				this.OnPropertyValueChange(_.object_id,_object_id,value);
				this._object_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string tableName
		{
			get{ return _tableName; }
			set
			{
				this.OnPropertyValueChange(_.tableName,_tableName,value);
				this._tableName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string tableDescription
		{
			get{ return _tableDescription; }
			set
			{
				this.OnPropertyValueChange(_.tableDescription,_tableDescription,value);
				this._tableDescription=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string tableOwner
		{
			get{ return _tableOwner; }
			set
			{
				this.OnPropertyValueChange(_.tableOwner,_tableOwner,value);
				this._tableOwner=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string creater
		{
			get{ return _creater; }
			set
			{
				this.OnPropertyValueChange(_.creater,_creater,value);
				this._creater=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? createTime
		{
			get{ return _createTime; }
			set
			{
				this.OnPropertyValueChange(_.createTime,_createTime,value);
				this._createTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string remark
		{
			get{ return _remark; }
			set
			{
				this.OnPropertyValueChange(_.remark,_remark,value);
				this._remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.object_id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.object_id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.class_id,
				_.object_id,
				_.tableName,
				_.tableDescription,
				_.tableOwner,
				_.creater,
				_.createTime,
				_.status,
				_.remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._class_id,
				this._object_id,
				this._tableName,
				this._tableDescription,
				this._tableOwner,
				this._creater,
				this._createTime,
				this._status,
				this._remark};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_table_dic");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field class_id = new Field("class_id","Sys_table_dic","class_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field object_id = new Field("object_id","Sys_table_dic","object_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tableName = new Field("tableName","Sys_table_dic","tableName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tableDescription = new Field("tableDescription","Sys_table_dic","tableDescription");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tableOwner = new Field("tableOwner","Sys_table_dic","tableOwner");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field creater = new Field("creater","Sys_table_dic","creater");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field createTime = new Field("createTime","Sys_table_dic","createTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field status = new Field("status","Sys_table_dic","status");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remark = new Field("remark","Sys_table_dic","remark");
		}
		#endregion


	}
}

